{{- $fullName := include "landing-client.fullname" . -}}
  {{- $servicePort := .Values.service.port -}}
  {{- $ingressPaths := .Values.ingress.paths -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "landing-client.name" . }}
    helm.sh/chart: {{ include "landing-client.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- range $ingressPaths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
          {{- end }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.certificate.secretName }}
