{{- $services := .Values.ingress.services -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ include "common-service-api-ingress.name" . }}
    helm.sh/chart: {{ include "common-service-api-ingress.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- range $services }}
          - path: {{ .path }}
            backend:
              serviceName: {{ .name }}
              servicePort: {{ .port }}
          {{- end }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.certificate.secretName }}
