ingress:
  class: nginx
  annotations:
    certmanager.k8s.io/cluster-issuer: issuer-letsencrypt
  host: api.odlli.com
  services:
    - name: prod-notification-service
      port: 8080
      path: /notification

certificate:
  name: api-odlli-com-crt
  secretName: api-odlli-com-tls
  issuer:
    name: issuer-letsencrypt