apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuer.name }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ax.barchuk@gmail.com
    privateKeySecretRef:
      name: {{ .Values.issuer.name }}
    # Enable the HTTP-01 challenge provider
    http01: {}